concourse-url: http://127.0.0.1:8080/ # e.g. http://192.168.100.4:8080/
concourse-team: main  # e.g. main
concourse-username: admin  # e.g. admin
concourse-password: admin
concourse-pipeline-name: ship-it-enhanced # e.g. shipt-it-enhanced