---
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/ibrahimparvez2/concourse-demo.git
    branch: main
jobs:
- name: read-the readme
  plan:
  - get: git-repo
    trigger: true
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/buildroot
          tag: "git"
      inputs:
        - name: git-repo
      outputs:
        - name: branch-info
      run:
        path: cat
        args: ["git-repo/README.md"]